# Generated by Django 6.1 on 2026-08-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curd_State_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
