# Generated by Django 6.1 on 2026-08-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curd_State_App', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curd_State_App.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curd_State_App.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curd_State_App.state')),
            ],
        ),
    ]
